# Generated by Django 4.0.4 on 2022-09-11 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_vatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='vatar',
            new_name='avatar',
        ),
    ]
